<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>eShopWinForms</RootNamespace>
    <AssemblyName>eShopWinForms</AssemblyName>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.2" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.11" />
    <PackageReference Include="System.ServiceModel.Http" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="6.0.0" />
    <PackageReference Include="CoreWCF.Primitives" Version="1.9.1" />
    <PackageReference Include="CoreWCF.ConfigurationManager" Version="1.9.1" />
    <PackageReference Include="CoreWCF.Http" Version="1.9.1" />
    <PackageReference Include="CoreWCF.WebHttp" Version="1.9.1" />
    <PackageReference Include="CoreWCF.NetTcp" Version="1.9.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Connected Services\eShopServiceReference\Reference.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Reference.svcmap</DependentUpon>
    </Compile>
    <None Include="Connected Services\eShopServiceReference\CatalogService.wsdl" />
    <None Include="Connected Services\eShopServiceReference\CatalogService.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Include="Connected Services\eShopServiceReference\CatalogService1.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Include="Connected Services\eShopServiceReference\CatalogService2.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Include="Connected Services\eShopServiceReference\CatalogService3.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Include="Connected Services\eShopServiceReference\eShopWinForms.eShopServiceReference.CatalogBrand.datasource">
      <DependentUpon>Reference.svcmap</DependentUpon>
    </None>
    <None Include="Connected Services\eShopServiceReference\eShopWinForms.eShopServiceReference.CatalogItem.datasource">
      <DependentUpon>Reference.svcmap</DependentUpon>
    </None>
    <None Include="Connected Services\eShopServiceReference\eShopWinForms.eShopServiceReference.CatalogType.datasource">
      <DependentUpon>Reference.svcmap</DependentUpon>
    </None>
    <None Include="Connected Services\eShopServiceReference\eShopWinForms.eShopServiceReference.DiscountItem.datasource">
      <DependentUpon>Reference.svcmap</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\Images\backgroundPhoto.jpg" />
    <Content Include="Assets\Images\Catalog\1.png" />
    <Content Include="Assets\Images\Catalog\10.png" />
    <Content Include="Assets\Images\Catalog\11.png" />
    <Content Include="Assets\Images\Catalog\12.png" />
    <Content Include="Assets\Images\Catalog\13.png" />
    <Content Include="Assets\Images\Catalog\14.png" />
    <Content Include="Assets\Images\Catalog\2.png" />
    <Content Include="Assets\Images\Catalog\3.png" />
    <Content Include="Assets\Images\Catalog\4.png" />
    <Content Include="Assets\Images\Catalog\5.png" />
    <Content Include="Assets\Images\Catalog\6.png" />
    <Content Include="Assets\Images\Catalog\7.png" />
    <Content Include="Assets\Images\Catalog\8.png" />
    <Content Include="Assets\Images\Catalog\9.png" />
    <Content Include="Assets\Images\LoginLogo.png" />
    <Content Include="Assets\Images\profile.png" />
    <Content Include="Assets\LockScreenLogo.scale-100.png" />
    <Content Include="Assets\LockScreenLogo.scale-125.png" />
    <Content Include="Assets\LockScreenLogo.scale-150.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-400.png" />
    <Content Include="Assets\SplashScreen.scale-100.png" />
    <Content Include="Assets\SplashScreen.scale-125.png" />
    <Content Include="Assets\SplashScreen.scale-150.png" />
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\SplashScreen.scale-400.png" />
    <Content Include="Assets\Square150x150Logo.scale-100.png" />
    <Content Include="Assets\Square150x150Logo.scale-125.png" />
    <Content Include="Assets\Square150x150Logo.scale-150.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-400.png" />
    <Content Include="Assets\Square310x310Logo.scale-100.png" />
    <Content Include="Assets\Square310x310Logo.scale-125.png" />
    <Content Include="Assets\Square310x310Logo.scale-150.png" />
    <Content Include="Assets\Square310x310Logo.scale-200.png" />
    <Content Include="Assets\Square310x310Logo.scale-400.png" />
    <Content Include="Assets\Square44x44Logo.scale-100.png" />
    <Content Include="Assets\Square44x44Logo.scale-125.png" />
    <Content Include="Assets\Square44x44Logo.scale-150.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-400.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-16.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-16_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-20.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-20_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-256.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-256_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-30.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-30_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-32.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-32_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-36.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-36_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-40.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-40_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-48.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-48_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-60.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-60_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-64.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-64_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-72.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-72_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-80.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-80_altform-unplated.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-96.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-96_altform-unplated.png" />
    <Content Include="Assets\Square71x71Logo.scale-100.png" />
    <Content Include="Assets\Square71x71Logo.scale-125.png" />
    <Content Include="Assets\Square71x71Logo.scale-150.png" />
    <Content Include="Assets\Square71x71Logo.scale-200.png" />
    <Content Include="Assets\Square71x71Logo.scale-400.png" />
    <Content Include="Assets\StoreLogo.scale-100.png" />
    <Content Include="Assets\StoreLogo.scale-125.png" />
    <Content Include="Assets\StoreLogo.scale-150.png" />
    <Content Include="Assets\StoreLogo.scale-200.png" />
    <Content Include="Assets\StoreLogo.scale-400.png" />
    <Content Include="Assets\Tiles\1.png" />
    <Content Include="Assets\Tiles\2.png" />
    <Content Include="Assets\Tiles\3.png" />
    <Content Include="Assets\Tiles\4.png" />
    <Content Include="Assets\Tiles\5.png" />
    <Content Include="Assets\Wide310x150Logo.scale-100.png" />
    <Content Include="Assets\Wide310x150Logo.scale-125.png" />
    <Content Include="Assets\Wide310x150Logo.scale-150.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
    <Content Include="Assets\Wide310x150Logo.scale-400.png" />
    <None Include="Connected Services\eShopServiceReference\Reference.svcmap">
      <Generator>WCF Proxy Generator</Generator>
      <LastGenOutput>Reference.cs</LastGenOutput>
    </None>
    <None Include="Connected Services\eShopServiceReference\configuration.svcinfo" />
    <None Include="Connected Services\eShopServiceReference\configuration91.svcinfo" />
    <None Include="Connected Services\eShopServiceReference\CatalogService.disco" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services\" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadataStorage Include="Connected Services\eShopServiceReference\" />
  </ItemGroup>
</Project>